name: 🏗️ iOS Build & Deploy to App Store

on:
  workflow_dispatch:   # manual trigger
  # push:
  #   branches: [develop, feature/*]  # optional trigger for testing

jobs:
  build:
    runs-on: macos-26

    env:
      KEYCHAIN_PASSWORD: temp_pass
      CERT_P12_PASSWORD: ${{ secrets.DISTRIBUTION_CERT_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}

    steps:
      # 1️⃣ Checkout source code
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Display Xcode version for debugging
      - name: 🧰 Setup Xcode
        run: xcodebuild -version

      # 3️⃣ Import signing certificate (.p12)
      - name: 🔑 Import Distribution Certificate
        run: |
          echo "${{ secrets.DISTRIBUTION_CERT_P12 }}" | base64 --decode > distribution.p12

          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import distribution.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "$CERT_P12_PASSWORD" \
            -T /usr/bin/codesign

          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" ~/Library/Keychains/build.keychain

          echo "✅ Certificate imported successfully."

      # 4️⃣ Create App Store Connect API key file
      - name: 🔑 Setup App Store Connect API Key
        run: |
          mkdir -p ~/private_keys
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > ~/private_keys/AuthKey_${APP_STORE_CONNECT_KEY_ID}.p8
          echo "✅ App Store Connect API key created"

      # 5️⃣ Build & archive (automatic provisioning via API key)
      - name: 🏗️ Build and Archive
        run: |
          xcodebuild clean archive \
            -project "Action Demo.xcodeproj" \
            -scheme "Action Demo" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$PWD/build/Action Demo.xcarchive" \
            -allowProvisioningUpdates \
            -authenticationKeyPath ~/private_keys/AuthKey_${APP_STORE_CONNECT_KEY_ID}.p8 \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_ID" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID" \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Automatic
          echo "✅ Archive created successfully at build/Action Demo.xcarchive"

      # 6️⃣ Create ExportOptions.plist
      - name: 📝 Create Export Options
        run: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>${APPLE_TEAM_ID}</string>
              <key>uploadSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          echo "✅ ExportOptions.plist created"

      # 7️⃣ Export IPA
      - name: 📦 Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/Action Demo.xcarchive" \
            -exportPath "$PWD/build" \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates \
            -authenticationKeyPath ~/private_keys/AuthKey_${APP_STORE_CONNECT_KEY_ID}.p8 \
            -authenticationKeyID "$APP_STORE_CONNECT_KEY_ID" \
            -authenticationKeyIssuerID "$APP_STORE_CONNECT_ISSUER_ID"
          echo "✅ IPA exported successfully"

      # 8️⃣ Upload to App Store Connect
      - name: 🚀 Upload to App Store Connect
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file "$PWD/build/Action Demo.ipa" \
            --apiKey "$APP_STORE_CONNECT_KEY_ID" \
            --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID"
          echo "✅ Successfully uploaded to App Store Connect"
